### ISSUE TITLE
Tarefas Iniciais

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#1]
Oi, @priscilavalverdes 
Vamos centralizar todas as etapas do projeto aqui no github.
Assim podemos deixar tudo transparente e temos controle das alterações.

Pensei em algumas tarefas iniciais pra vc se acostumar com o processo de trabalho do GitHub. Conforme você finalizar cada item, pode marcar o box:

- [x] Clonar o repositório para seu perfil
- [x] Criar um novo branch com seu nome (aconselho que essas duas primeiras etapas sejam feitas dentro do VSCode)
- [x] Atualizar o README.md incluíndo informações sobre a  bolsista, vigência da bolsa, objetivos gerais.
  - [x] Antes de atualizar o documento, assistir ao minicurso [**Uma introdução ao Markdown e suas possibilidades no ensino e divulgação científica** ](https://youtu.be/TtnATYla2gE)
- [x] Criar pasta e um novo documento para o cronograma da pesquisa ( pode ser um rascunho em docx baseado no cronograma do plano de trabalho);
- [x] Fazer commit das alterações para o branch `priscila`
- [x] Criar um pull request para a atualização do branch `priscila` para o branch `main` 

Se precisar de mais informações, há um curso sobre Git e Github no Curso em Vídeo que pode ajudar: [Curso de Git e GitHub](https://youtube.com/playlist?list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA)

Conforme realizar as atividades, pode comentar aqui nesse ticket o que já fez, ou as suas dúvidas de como fazer.

**Comment by ericbrasiln** [comment]
@priscilavalverdes 
Agora que vc já fez o PR e está tudo ok, pode marcar a última tarefa e fechar esse ticket clicando em `Close issue` 
Automaticamente ele vai para o painel `Done` do projeto.
Vamos marcar um encontro pra pensar nas próximas atividades.

**Comment by priscilavalverdes** [comment]
Finalizado. @ericbrasiln  eu fiz mas ainda estou com dificuldade, estou fazendo meio que no tato. Vou refazer o curso de github porque ainda estou me sentindo meio perdida aqui.
