### ISSUE TITLE
Planilha de docentes_unilab

### ISSUE THREAD

**Issue by priscilavalverdes** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#10]
@ericbrasiln vc quer uma planilha geral com o contato de todos os docentes das universidades e uma separada para o conjunto de docentes elencados por universidade? é isso?

**Comment by ericbrasiln** [comment]
Oi, @priscilavalverdes 
Eu acho melhor que a gente crie uma planilha de docentes para cada universidade.
Elas estando em `csv` podem ser facilmente fundidas e trabalhadas em conjunto com pandas, por exmeplo.
