### ISSUE TITLE
# Criação do formulário

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#11]
Precisamos utilizar o mês de fevereiro para criar o formulário e finalizar a estratégia de envio para os docentes.

- [x] Leitura de bilbiografia sobre o tema
     - [x] [DA COSTA ANDRES, Fabiane; ANDRES, Silvana Carloto; MORESCHI, Claudete; et al. A utilização da plataforma Google Forms em pesquisa acadêmica: relato de experiência. Research, Society and Development, v. 9, n. 9, p. e284997174–e284997174, 2020.](https://doi.org/10.33448/rsd-v9i9.7174)
     - [x] [DA SILVA MOTA, Janine. Utilização do google forms na pesquisa acadêmica. Humanidades & Inovação, v. 6, n. 12, p. 371–373, 2019.](https://revista.unitins.br/index.php/humanidadeseinovacao/article/view/1106)
- [x] #12
- [x] Criação do formulário no Google Forms
- [x] Revisão do formulário e finalização

**Comment by priscilavalverdes** [comment]
Ciente.

**Comment by priscilavalverdes** [comment]
@ericbrasiln Fiz do outro jeito para testar, achei q pinnando ele criava uma nova issue dentro da mesma tarefa, mas ele transforma em uma outra,

**Comment by ericbrasiln** [comment]
Oi @priscilavalverdes 
Fiz agora commit com as correções das planilhas e [criação do rascunho](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/main/Question%C3%A1rio/draft.md) em Markdow.
Dei uma boa mexida. Ainda precisamos acertar algumas coisas nele.
Veja o que vc acha das perguntas, das sessões, etc.

**Comment by priscilavalverdes** [comment]
> Oi @priscilavalverdes Fiz agora commit com as correções das planilhas e [criação do rascunho](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/main/Question%C3%A1rio/draft.md) em Markdow. Dei uma boa mexida. Ainda precisamos acertar algumas coisas nele. Veja o que vc acha das perguntas, das sessões, etc.

Certo. Eu vejo hoje.

**Comment by priscilavalverdes** [comment]
@ericbrasiln , ficou bem legal. Fiquei com dúvida sobre a visualização das questões, não sei se é falha na minha interface ou se é referente a alguma tradução do github das questões para o inglês e depois para o português novamente. Algumas fases estão meio embaralhadas.

Você quer que eu transfira o questionário para o google forms?

**Comment by ericbrasiln** [comment]
Olhando no GitHub não aparece assim?

https://user-images.githubusercontent.com/58128421/155236904-ce688885-1ca1-4a3b-82a5-22b151e0e456.mp4

Criei a base para o formulário e te coloquei como editora: https://forms.gle/GSV8F4k6KY7um7fM7

Há uma bibliografia sobre uso de formulário em pesquisas acadêmicas que acho que devíamos ler rapidamente antes de fechar essa etapa. 
Vou adicionar nas tarefas desse ticket.

**Comment by priscilavalverdes** [comment]
> Olhando no GitHub não aparece assim?
> 
>  gt.mp4 

Não. O meu sempre tem dado essas divergências.

> Criei a base para o formulário e te coloquei como editora: https://forms.gle/GSV8F4k6KY7um7fM7
> 
> Há uma bibliografia sobre uso de formulário em pesquisas acadêmicas que acho que devíamos ler rapidamente antes de fechar essa etapa. Vou adicionar nas tarefas desse ticket.

Ok.

**Comment by priscilavalverdes** [comment]
Sobre o questionário:
 
1. Todas as perguntas serão de resposta obrigatória?
2.  As questões: 12, 13, 14 e 16 serão escalonadas mesmo ou serão "polar"?
3. Não entendi as respostas da questão 16 muito bem
4. Não entendi a questão 17 muito bem.

@ericbrasiln

**Comment by priscilavalverdes** [comment]
@ericbrasiln Eu coloquei uma descriçãozinha sobre o q possivelmente estamos buscando entender com as perguntas das sessões, mas fiquei com dúvida se a descrição é uma introdução sobre a temática específica ou se é realmente sobre o o bloco.

**Comment by priscilavalverdes** [comment]
@ericbrasiln o que vc acha de colocar uma questão sobre materialidade? Ex. se uma fonte não-digital que foi digitalizada para o repósitório modifica a possibilidade de  apuração da fonte, se interfere na heurística... Já tem uma questão sobre metodologia, mas pensei em chamar a atenção para a rematerialização...

**Comment by ericbrasiln** [comment]
Oi @priscilavalverdes 
Revisei o formulário, incluí uma seção sobre o que os docentes querem aprender sobre isso.
veja o que acha.

**Comment by priscilavalverdes** [comment]
@ericbrasiln . Ficou bem legal. Gostei também dos repositórios já estarem listados. Sobre o termo de consentimento, vi que vc editou tbm, chegamos no texto final do termo então? Vou tentar colocar a caixa de aceite.

**Comment by ericbrasiln** [comment]
Sim, vou fechar o ticket
