### ISSUE TITLE
Troca de bolsista

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#17]
Oi @priscilavalverdes 

Só falta o relatório parcial em pdf gerado nesse [link](https://proppg.unilab.edu.br/forms/relatorio-parcial-IC/).
Mas tembém pensei em mais algumas coisas:

- [x] Finalizar o relatório parcial e me enviar por email (até amanhã pela manhã, 07/03)
- [x] Ajudar na formação da Ana nos aspectos técnicos do projeto:
   - [x] Github
   - [x] explicar o formulário
   - [x] planilhas em csv
   - [x] markdown

**Comment by priscilavalverdes** [comment]
> Oi @priscilavalverdes
> 
> Só falta o relatório parcial em pdf gerado nesse [link](https://proppg.unilab.edu.br/forms/relatorio-parcial-IC/). Mas tembém pensei em mais algumas coisas:
> 
>     * [x]  Finalizar o relatório parcial e me enviar por email (até amanhã pela manhã, 07/03)
> 
>     * [ ]  Ajudar na formação da Ana nos aspectos técnicos do projeto:
>       
>       * [ ]  Github
>       * [ ]  explicar o formulário
>       * [ ]  planilhas em csv
>       * [ ]  markdown

Ajudo sim. Vou combinar com ela.

**Comment by priscilavalverdes** [comment]
@ericbrasiln , estava vendo com Carol algumas funções do github. Demos uma pincelada sobre o github e o csv. Combinamos de Carol fazer o curso em vídeo e irmos tirando as dúvidas.

 1. Preciso que vc por favor adicione ela ao repositório pois não tenho permissão para adicioná-la (AnaCarolinaVeloso).
 
 2. Sobre a utilização do github, Carol vai usar o github desktop? Não estou conseguindo criar uma branch sem ser por comando, github desktop ou vscode.

**Comment by ericbrasiln** [comment]
Já convidei a Ana.

Acho melhor usar por aqui mesmo. A criação do branch acontece na hora de fazer o commit

**Comment by priscilavalverdes** [comment]
ok.
