### ISSUE TITLE
Tarefa para exercitar funções

### ISSUE THREAD

**Issue by priscilavalverdes** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#20]
- [x] Ler o readme.md com as informações do projeto. [Acesse aqui](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#readme)
- [ ] Responder com uma mensagem a esta tarefa.
- [ ] Usar um emoticon para esta tarefa.
- [ ] Mudar o responsável desta tarefa para outra pessoa do repositório. **(Assigned)**
- [ ] Criar uma etiqueta com o nome "resolvido". **(Labels -- edit labels -- new labels)**
- [ ] Mudar a etiqueta desta tarefa para "resolvido"

**Comment by ericbrasiln** [comment]
@AnaCarolinaVeloso 
Você pode resolver as tarefas dessa issue.
É mais um exercício (apesar de você já estar sabendo das coisas.) 😄
