### ISSUE TITLE

Tarefas para a semana

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#21]
- [x] Criar um branch `ana-01`
- [x] Realizar as alterações diretamente em cada arquivos do repositório (conferindo se está no branch `ana-01` no momento de efetuar o commit):
    - [x] conferir, completar e corrigir a planilha [contatos](Contatos/Contatos.csv)
    - [x] #23
    - [x] No interior do diretório [Contatos](Contatos), criar um arquivo chamado `modelo_email.md` contendo o modelo de email que será enviado para as coordenações/chefias dos cursos.
- [x] Após todas as alterações estarem finalizadas:
    - [x] Criar um Pull Request para o branch `main`
    - [x] Se inclua no menu "Assignees"
    - [x] Me adicione como revisor ("Reviewers").
    - [x] Tenha certeza de que não há bugs detectados e que seu PR está apto para ser mesclado ("Merge") ao branch principal `main`. 
- [x] Revisar o [questionário](https://forms.gle/SadZWGXfXyVyH5tZ9) - colocar seu nome e ver se encontra algum problema.
- [x] Responder todo o questionário e calcular o tempo de resposta média. Esse dado deve constar no email.
- [x] A cada etapa, marcar nessa issue o avanço.
- [x] Comentar essa issue com as dúvidas e sugestões que surgirem.

**Comment by AnaCarolinaVeloso** [comment]
na #23 eu acabei indo no ciclo com o ponto no centro, não consegui desfazer, me achando ainda kkk

**Comment by AnaCarolinaVeloso** [comment]
A lista de e-mail tá completa, mas alguns dados como: secretaria; horário de atendimento; atendimento etc. tá com lacunas. Enviamos o e-mails para as coordenações e nas que estão com esses dados faltando, quando tivermos retorno, podemos pedir os dados que faltam ?
Pq seria muito bom enviarmos esse formulário agora na primeira semana de abril.

**Comment by ericbrasiln** [comment]
Sim, essas outras informações era apenas para garantir, se não tivermos retorno por email.

**Comment by AnaCarolinaVeloso** [comment]
Levei 8 minutos para responder o formulário, lendo todas as informações e sem preencher as respostas abertas, podemos colocar uma média de 7 a 15 minutos.

**Comment by ericbrasiln** [comment]
Tudo certo @AnaCarolinaVeloso 
Revisei o [modelo de email](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/main/Contatos/modelo_email.md) e já solicitei a criação do email para o projeto.
