### ISSUE TITLE
Leituras para abril

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#25]
Bom dia @AnaCarolinaVeloso 

Após o envio dos emails, temos que aguardar o retorno das respostas ao formulário.

Nesse período, indico que você leia os seguintes textos:

- [x] [COBURN, Jon. Defending the digital: Awareness of digital selectivity in historical research practice. Journal of Librarianship and Information Science, p. 1–13, 2020.](https://journals.sagepub.com/doi/10.1177/0961000620918647)
- [x] JENSEN, Helle Strandgaard. Digital Archival Literacy for (all) Historians. Media History, v. 27, n. 2, p. 251–265, 2021. (esse eu te envio no privado)

Sei que estão em inglês e isso é um desafio. Mas acho que é importante para o projeto e para sua formação.

@priscilavalverdes se vc quiser e tiver tempo, podemos discutir eles juntos (vc já leu o primeiro. Pode dar um help pra Ana?)

Abraços

**Comment by priscilavalverdes** [comment]
Oi @ericbrasiln , combinado!! Quero discutir e posso ajudar Carol.
