### ISSUE TITLE
Nova metodologia de envio de e-mails

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#28]
Em função do pouco engajamento das coordenações de curso na divulgação das mensagens solicitando preenchimento do formulário, alteramos a metdologia e prazos.

@AnaCarolinaVeloso por favor  explique nessa issue essas mudanças.

**Comment by ericbrasiln** [comment]
@AnaCarolinaVeloso 
Sei que vc está finalizando o resumo para a Semuni, mas vc precisa registrar aqui a metodologia do envio de emails diretamente para os docentes.

Não tem lista de docentes da UFRB na pasta [Contatos](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/tree/main/Contatos) não tem a lista de contatos da UFRB, UFSB, UFOB. Precisamos criar e enviar os e-mails. Se não temos nenhum email dessas IES é preciso registrar isso aqui.

- [ ] e-mails UFRB
- [ ] e-mails UFSB
- [ ] e-mails UFOB
- [x] Contato direto com docentes do colegiado da Unilab @ericbrasiln 
- [x] Tentar contato direto com alguns docentes de outras IES @ericbrasiln

**Comment by ericbrasiln** [comment]
Entrei em contato com o colegiado de história da Unilab pedindo a colaboração e com alguns outros professores que tenho contato mais próximo.
Entrei em contato diretamente com a coordenadora do curso da UFRB pedindo a lista de emails dos docentes
Os e-mails foram enviados da minha conta pessoal com cópia para o emails do projeto.
Vou criar a lista de contatos da UFRB com os emails que eu já possuo. O resto incluímos quando a coordenadora responder.

**Comment by AnaCarolinaVeloso** [comment]
Ok prof. 

Então tivemos a coleta de dados feita por três métodos:
1- Busca na web em canais oficiais da instituição/curso (onde obtivemos ao menos o nome dos professores, em alguns o lattes ou o e-mail)
2- Para os que só tínhamos o nome e o lattes, seguimos a metodologia de consultar os cinco ultimo trabalhos/artigos submetidos no lattes com o objetivo de coletar o e-mail 
3- Entrar em contato de forma particular com as coordenações onde não obtivemos nenhum dado do corpo docente com o método 1.

**Comment by AnaCarolinaVeloso** [comment]
Por conta dessas alterações, prorrogamos três vezes a data para resposta do questionário:
- 30/ 04/ 2022  
- 10/ 05/ 2022 
- 27/ 05/ 2022
