### ISSUE TITLE
Organização dos dados para análise

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#30]
Oi @AnaCarolinaVeloso 

Vamos criar um checklist de tarefas relacionadas com a organização dos dados para análise.

- [x] Criar pasta com a planilha de respostas
- [x] Calcular o número de emails eviados e a porcentagem de respostas
- [x] Criar um documento de texto simples explicando os dados de emails enviados, porcentagem de resposta e total de respostas.

Se pensar em mais alguma coisa para inserir dessa lista, pode comentar aqui embaixo.
Dá pra fechar isso até a próxima quarta?

**Comment by AnaCarolinaVeloso** [comment]
Até amanhã não, mas termino até sexta.

**Comment by ericbrasiln** [comment]
Oi @AnaCarolinaVeloso 
Crie uma pasta com a planilha das respostas, e o texto com a análise inicial dos emails enviados e as respostas obtidas (como vc me enviou no telegram).
Pode me enviar a pasta por email (ericbrasiln@proton.me) e então eu atualizo aqui no repositório.
Depois disso, fechamos essa issue e partimos para análise final.
Abraços

**Comment by ericbrasiln** [comment]
@AnaCarolinaVeloso 
Incluí os arquivos que você me enviou e vou criar uma nova issue pra gente fechar a estrutura da análise.
