### ISSUE TITLE
Análise dos dados

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#32]
Olá, @AnaCarolinaVeloso 

Montei um [roteiro para análise dos dados](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/main/dados/roteiro-analise.md).

O relatório deve apresentar a metodologia e do fluxo de trabalho, assim como a apresentação geral dos dados e a breve análise (que deve seguir a mesma estrutura que estou propondo no roteiro.

- [x] Criar o roteiro no repositório @ericbrasiln
- [x] escrever a análise respondendo ao roteiro - @AnaCarolinaVeloso 
- [x] criar issue relativa ao Relatório Final - @ericbrasiln

**Comment by ericbrasiln** [comment]
Oi @AnaCarolinaVeloso 

Incluí o [roteiro de análise](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/main/dados/roteiro-analise.md) e assim que você conseguir respondê-lo, fazemos o relatório final.

A parte da metodologia e outras questões já estão descritas no [relatório parcial](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/main/Relatorios/Relatorio_parcial.md).

**Comment by AnaCarolinaVeloso** [comment]
Essa pergunta sobre semelhança entre os repositórios utilizados é complicada pra responder. Seria necessário fazer uma análise das características de  cada um para traçar as semelhanças, tipo o que fizemos para a elaboração do mapa das Hemerotecas. Podemos deixar como tarefa para um outro momento.

**Comment by ericbrasiln** [comment]
> Essa pergunta sobre semelhança entre os repositórios utilizados é complicada pra responder. Seria necessário fazer uma análise das características de cada um para traçar as semelhanças, tipo o que fizemos para a elaboração do mapa das Hemerotecas. Podemos deixar como tarefa para um outro momento.

Vc tem razão, talvez valha a pena deixar isso como ideia para o futuro artigo. Talvez dê apenas para separar por categorias: repositórios públicos de fontes; hemerotecas; bibliotecas digitais; acervos privados; acervos temáticos; repositórios de universidades.

O que acha @AnaCarolinaVeloso ?

**Comment by AnaCarolinaVeloso** [comment]
Vou olhar e organizar pq ficou muito solto. E vejo como separa em grupos ou pensar em oura forma.

**Comment by AnaCarolinaVeloso** [comment]
Estou com duvida sobre a relação que vc tenta estabelecer entre a Q.9 e 10. 
Pra ficar mais rápido me explique por áudio no telegram ou em qualquer outra rede. Claro se vc poder.
