### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by priscilavalverdes** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#4]
Ainda estou com dificuldade para fazer o pull request no branch principal . Só consegui publicar a ramificação e a alteração  no meu branch.

**Comment by ericbrasiln** [comment]
Oi @priscilavalverdes 
Eu não sei porque eu não recebi notificação desse ticket.
Quando vc criar issues me marque com meu usuário no texto @ericbrasiln 

Eu acho o jeito mais fácil de fazer pull request é diretamente pelo site do github. 

https://user-images.githubusercontent.com/58128421/149432884-9bbccfad-2dc4-411b-b49e-ec6303759b15.mp4

Abraços.
