### ISSUE TITLE
Cronograma e Contatos

### ISSUE THREAD

**Issue by ericbrasiln** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#7]
Oi, @priscilavalverdes 
Fiz commit incluindo pasta com cronograma e contatos em `csv`.

Agora temos algumas tarefas a realizar:

## [Cronograma](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/98bd9ae071059f7b775918b21e8b49c3a6fb7d53/Cronograma-de-atividades)

- [x] Conferir se as tarefas estão pertinentes
- [x] Conferir se as datas estão pertinentes

## Contatos

- [x] Incluir os dados na planilha [Contatos_IES](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/98bd9ae071059f7b775918b21e8b49c3a6fb7d53/Contatos/Contatos_IES.csv#L8)
- [x] Incluir os dados na planilha [docentes_unilab](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/98bd9ae071059f7b775918b21e8b49c3a6fb7d53/Contatos/docentes_unilab.csv)
- [x] Criar planilhas para todos os cursos a partir do modelo da planilha [docentes_unilab](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/blob/98bd9ae071059f7b775918b21e8b49c3a6fb7d53/Contatos/docentes_unilab.csv)

**OBS**: os dados inseridos nessas planilhas devem públicos e que constem nos sites oficiais das IES.

Ao concluir as tarefas, pode criar um PR e fazer o mesmo processo do anterior.

**Comment by priscilavalverdes** [comment]
Tarefas finalizadas.
