### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by priscilavalverdes** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#8]
@ericbrasiln 
1. A conferência das datas é pelo plano de trabalho ou frequência?
2. Para alterar a planilha, é para ser feito no VScode e depois fazer um PR ou aqui no GH mesmo? 
OBS: Se for aqui, eu faço já direto no csv?

**Comment by ericbrasiln** [comment]
Oi,

1.  As coisas que vc já fez e colocou na frequência vc pode atualizar no cronograma. E o que ainda falta fazer é pra conferir se as datas que coloquei são pertinentes, se tem outras atividades pra incluir, etc.
2. Vc pode alterar no VSCode (ou mesmo alterar no excel se preferir e depois substituir na pasta do repositório no seu computador) e depois fazer commit para o seu branch e depois fazer o PR. Vc tb pode alterar direto no GH, mas como é um csv, talvez fique melhor pra vc visualizar e alterar no excel.

Essas dúvidas que são diretamente relacionadas ao ticket #7 podem ser comentadas direto lá no ticket.

Para vc ver os tickets já fechados, vc tem que procurar em `issues > closed` (esse link [aqui](https://github.com/Curso-de-Historia-Unilab-Males/historia-digital-PIBIC/issues?q=is%3Aissue+is%3Aclosed) leve direto pra elas).

Se respondi todas as suas dúvidas, pode fechar esse ticket.
