### ISSUE TITLE
Edição na fluxo de atividades

### ISSUE THREAD

**Issue by priscilavalverdes** [Curso-de-Historia-Unilab-Males/historia-digital-PIBIC#9]
@ericbrasiln , tem alguma configuração específica de teclado ou alguma outra coisa para editar no próprio GH? estou tentando aletrar a planilha de atividades mas os comandos não estão correspondentes, tento apagar um(x) por exemplo, com delete e ele apaga vários caracteres, também não consigo inserir outro no lugar.

**Comment by ericbrasiln** [comment]
Para alterar arquivos diretamente no GH vc precisa clicar no 'lápis' pra editar (veja a imagem 1)
Mas pra você editar uma planilha em csv é melhor baixar ela e editar no excel, pq o csv pode ser difícil de visualizar em sua forma de arquivo de texto (imagem 2)

## Image 1

![2022-01-27_22-55](https://user-images.githubusercontent.com/58128421/151473817-e773e9df-1344-417c-981f-55b18c976bab.png)

## Imagem 2

![2022-01-27_22-57](https://user-images.githubusercontent.com/58128421/151473831-24f876dc-7fa1-4958-9986-6eba902ed0c2.png)

Vc pode editar direto aí como na imagem 2 e ir clicando em `Preview changes` pra ver se está certo, mas é mais fácil no excel.

**Comment by priscilavalverdes** [comment]
Eu fiz isso, mas meu GH fica dando uns erros, parece que não aceita os comandos que eu dou. Vou baixar e editar.
